// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HelloAvro.DTO
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	/// <summary>
	/// Hello Avro examples here\r\n  See http://avro.apache.org/docs/1.7.5/idl.html for more info on\r\n  how you can express your data in the IDL syntax
	/// </summary>
	public abstract class HelloAvroProtocol : Avro.Specific.ISpecificProtocol
	{
		private static readonly Avro.Protocol protocol = Avro.Protocol.Parse(@"{""protocol"":""HelloAvroProtocol"",""namespace"":""HelloAvro.DTO"",""doc"":""Hello Avro examples here\\r\\n  See http://avro.apache.org/docs/1.7.5/idl.html for more info on\\r\\n  how you can express your data in the IDL syntax"",""types"":[{""type"":""record"",""name"":""ProjectDTO"",""namespace"":""HelloAvro.DTO"",""fields"":[{""name"":""ProjectId"",""type"":""int""},{""name"":""ProjectName"",""type"":""string""}]},{""type"":""record"",""name"":""EmployeeDTO"",""namespace"":""HelloAvro.DTO"",""fields"":[{""name"":""Name"",""type"":""string""},{""name"":""EmployeeId"",""type"":""int""},{""name"":""Reportees"",""type"":{""type"":""array"",""items"":""int""}},{""name"":""Notes"",""type"":[""null"",""string""]},{""name"":""ActiveProjects"",""type"":{""type"":""array"",""items"":""ProjectDTO""}},{""name"":""RawBytes"",""type"":""bytes""},{""name"":""StillWorksHere"",""type"":""boolean""}]},{""type"":""error"",""name"":""ServerError"",""namespace"":""HelloAvro.DTO"",""fields"":[{""name"":""message"",""type"":""string""}]}],""messages"":{""TransformName"":{""request"":[{""name"":""employee"",""type"":""EmployeeDTO""}],""response"":""string""},""hello"":{""request"":[{""name"":""name"",""type"":""string""}],""response"":""string""},""add"":{""request"":[{""name"":""arg1"",""type"":""int""},{""name"":""arg2"",""type"":""int""}],""response"":""int""},""divide"":{""request"":[{""name"":""arg1"",""type"":""int""},{""name"":""arg2"",""type"":""int""}],""response"":""int"",""errors"":[""ServerError""]},""heartbeat"":{""request"":[],""response"":""null"",""one-way"":true}}}");
		public Avro.Protocol Protocol
		{
			get
			{
				return protocol;
			}
		}
		public void Request(Avro.Specific.ICallbackRequestor requestor, string messageName, object[] args, object callback)
		{
			switch(messageName)
			{
				case "TransformName":
				requestor.Request<System.String>(messageName, args, callback);
				break;

				case "hello":
				requestor.Request<System.String>(messageName, args, callback);
				break;

				case "add":
				requestor.Request<System.Int32>(messageName, args, callback);
				break;

				case "divide":
				requestor.Request<System.Int32>(messageName, args, callback);
				break;

				case "heartbeat":
				requestor.Request<System.Object>(messageName, args, callback);
				break;
			};
		}
		public abstract string TransformName(HelloAvro.DTO.EmployeeDTO employee);
		public abstract string hello(string name);
		public abstract int add(int arg1, int arg2);
		public abstract int divide(int arg1, int arg2);
		public abstract void heartbeat();
	}
}
